### ISSUE TITLE
movement should be more smooth

### ISSUE THREAD

**Issue by JstRafau** [JstRafau/doodle_like#1]
Movement speed should accelerate and decelerate

**Comment by eatablekolas** [comment]
I'm not sure how you'd do this in Rust, but Godot has this nice function called `move_toward()`. You could probably use it for decelerating like this:
```gdscript
velocity.x = move_toward(velocity.x, 0, SPEED)
velocity.y = move_toward(velocity.y, 0, SPEED)
```

**Comment by JstRafau** [comment]
I used it, the syntax is a little bit different, but it indeed works, thanks 👍
